import React from 'react';
import { Switch } from './Switch';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Switch, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=11%3A6554', {
  props: {
    // These props were automatically mapped based on your linked code:
    checked: figma.boolean('Checked'),
    defaultChecked: figma.boolean('Checked'),
    disabled: figma.boolean('Disabled'),
    // No matching props could be found for these Figma properties:
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Hovered": "hovered",
    //   "Focused": "focused"
    // })
  },
  example: props => <Switch checked={props.checked} defaultChecked={props.defaultChecked} disabled={props.disabled} />,
});
