import React from 'react';
import { Avatar } from './Avatar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Avatar, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A21385', {
  props: {
    // These props were automatically mapped based on your linked code:
    appearance: figma.enum('Appearance', {
      Red: 'red',
      Orange: 'orange',
      Yellow: 'yellow',
      Green: 'green',
      Blue: 'blue',
      Violet: 'violet',
      Pink: 'pink',
    }),
    size: figma.enum('Shape', {
      Square: 's',
    }),
    shape: figma.enum('Shape', {
      Round: 'round',
      Square: 'square',
    }),
    showTwoSymbols: figma.boolean('Show 2 Symbol'),
    // No matching props could be found for these Figma properties:
    // "show2Symbol": figma.boolean('Show 2 Symbol'),
    // "indicator": figma.boolean('Indicator'),
    // "showImage": figma.boolean('Show Image')
  },
  example: props => (
    <Avatar
      name={/* TODO */}
      appearance={props.appearance}
      size={props.size}
      shape={props.shape}
      showTwoSymbols={props.showTwoSymbols}
    />
  ),
});
