import React from 'react';
import { Checkbox } from './Checkbox';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Checkbox, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=11%3A6491', {
  props: {
    // These props were automatically mapped based on your linked code:
    checked: figma.boolean('Checked'),
    defaultChecked: figma.boolean('Checked'),
    disabled: figma.boolean('Disabled'),
    // Indeterminate: нет совпадающего свойства в макете 6.0.6 (node 11:6491)
  },
  example: props => (
    <Checkbox
      checked={props.checked}
      defaultChecked={props.defaultChecked}
      disabled={props.disabled}
      indeterminate={false}
      indeterminateDefault={false}
    />
  ),
});

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=25590%3A25216',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.boolean('Checked'),
      defaultChecked: figma.boolean('Checked'),
      disabled: figma.boolean('Disabled'),
      // Indeterminate: нет совпадающего свойства в макете 6.0.6 (node 25590:25216)
    },
    example: props => (
      <Checkbox
        checked={props.checked}
        defaultChecked={props.defaultChecked}
        disabled={props.disabled}
        indeterminate={false}
        indeterminateDefault={false}
      />
    ),
  },
);
