import React from 'react';
import { Cards } from './Cards';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(Cards, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A221002', {
  props: {
    // No matching props could be found for these Figma properties:
    // "multipleSelection": figma.boolean('Multiple Selection'),
    // "showFunction": figma.boolean('Show Function'),
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Hovered": "hovered",
    //   "Focused": "focused"
    // }),
    // "checked": figma.boolean('Checked'),
    // "disabled": figma.boolean('Disabled'),
    // "outline": figma.boolean('Outline')
  },
  example: props => <Cards sysPalette={/* TODO */} description={/* TODO */} />,
});
