import React from 'react';
import Avatar from './Avatar.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Avatar, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A21523', {
  props: {
    show2Symbol: figma.boolean('Show 2 Symbol'),
    indicator: figma.boolean('Indicator'),
    showImage: figma.boolean('Show Image'),
    shape: figma.enum('Shape', {
      Round: 'round',
      Square: 'square',
    }),
    appearance: figma.enum('Appearance', {
      Red: 'red',
      Orange: 'orange',
      Yellow: 'yellow',
      Green: 'green',
      Blue: 'blue',
      Violet: 'violet',
      Pink: 'pink',
      Gray: 'gray',
    }),
  },
  example: props => <Avatar />,
});

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Avatar, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A21454', {
  props: {
    show2Symbol: figma.boolean('Show 2 Symbol'),
    indicator: figma.boolean('Indicator'),
    showImage: figma.boolean('Show Image'),
    shape: figma.enum('Shape', {
      Round: 'round',
      Square: 'square',
    }),
    appearance: figma.enum('Appearance', {
      Red: 'red',
      Orange: 'orange',
      Yellow: 'yellow',
      Green: 'green',
      Blue: 'blue',
      Violet: 'violet',
      Pink: 'pink',
      Gray: 'gray',
    }),
  },
  example: props => <Avatar />,
});
