import React from 'react';
import { Timeline } from './Timeline';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(Timeline, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=9209%3A4448', {
  props: {
    // No matching props could be found for these Figma properties:
    // "slotHoursContent": figma.instance('◆Slot Hours Content'),
    // "slotMinutesContent": figma.instance('◆Slot Minutes Content'),
    // "slotSecondsContent": figma.instance('◆Slot Seconds Content'),
    // "showSeconds": figma.boolean('Show Seconds')
  },
  example: props => <Timeline items={/* TODO */} />,
});
