import React from 'react';
import { IconPredefined } from './IconPredefined';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconPredefined,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A20749',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      appearance: figma.enum('Appearance', {
        Primary: 'primary',
        Neutral: 'neutral',
        Red: 'red',
        Orange: 'orange',
        Yellow: 'yellow',
        Green: 'green',
        Blue: 'blue',
        Violet: 'violet',
        Pink: 'pink',
      }),
      // No matching props could be found for these Figma properties:
      // "showBacground": figma.boolean('Show bacground'),
      // "decor": figma.enum('Decor', {
      //   "Round": "round",
      //   "Square": "square"
      // })
    },
    example: props => <IconPredefined appearance={props.appearance} icon={/* TODO */} />,
  },
);
