import React from 'react';
import { Counter } from './Counter';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Counter, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=7%3A4206', {
  props: {
    // These props were automatically mapped based on your linked code:
    appearance: figma.enum('Appearance', {
      Primary: 'primary',
      Neutral: 'neutral',
      Red: 'red',
    }),
    color: figma.enum('Color', {
      Accent: 'accent',
      Decor: 'decor',
    }),
  },
  example: props => <Counter value={/* TODO */} appearance={props.appearance} color={props.color} />,
});
