import React from 'react';
import { TextArea } from './TextArea';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(TextArea, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A47085', {
  props: {
    // No matching props could be found for these Figma properties:
    // "yScrolling": figma.boolean('Y scrolling'),
    // "showCopyButton": figma.boolean('Show Copy Button'),
    // "showClearButton": figma.boolean('Show Clear Button'),
    // "showSlotBottom": figma.boolean('Show Slot Bottom'),
    // "slotBottom": figma.instance('◆ Slot Bottom')
  },
  example: props => <TextArea value={/* TODO */} />,
});
