import React from 'react';
import SegmentedControl from './SegmentedControl.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SegmentedControl,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=20287%3A434',
  {
    props: {
      segmenteds: figma.instance('◆Segmenteds'),
      width: figma.enum('Width', {
        Auto: 'auto',
        Full: 'full',
      }),
    },
    example: props => <SegmentedControl />,
  },
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SegmentedControl,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=8747%3A207415',
  {
    props: {
      segmenteds: figma.instance('◆Segmenteds'),
      width: figma.enum('Width', {
        Auto: 'auto',
        Full: 'full',
      }),
    },
    example: props => <SegmentedControl />,
  },
);
