import React from 'react';
import { ChipChoiceDateRange } from './ChipChoiceDateRange';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ChipChoiceDateRange,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A152199',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.boolean('Disabled'),
      loading: figma.boolean('Loading'),
      open: figma.boolean('Open'),
      // No matching props could be found for these Figma properties:
      // "showClearButton": figma.boolean('Show Clear Button'),
      // "showIcon": figma.boolean('Show Icon'),
      // "showLabel": figma.boolean('Show Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused"
      // })
    },
    example: props => <ChipChoiceDateRange disabled={props.disabled} loading={props.loading} open={props.open} />,
  },
);
