import React from 'react';
import Tag from './Tag.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Tag, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A25226', {
  props: {
    appearance: figma.enum('Appearance', {
      Neutral: 'neutral',
      Primary: 'primary',
      Red: 'red',
      Orange: 'orange',
      Yellow: 'yellow',
      Green: 'green',
      Blue: 'blue',
      Violet: 'violet',
      Pink: 'pink',
    }),
    state: figma.enum('State', {
      Hovered: 'hovered',
      Focused: 'focused',
      Pressed: 'pressed',
      Default: 'default',
    }),
    removable: figma.boolean('Removable'),
  },
  example: props => <Tag />,
});
