import React from 'react';
import { CrumbsTypography } from './CrumbsTypography';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CrumbsTypography,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A31334',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "showIcon": figma.boolean('Show Icon'),
      // "open": figma.boolean('Open'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused"
      // }),
      // "current": figma.boolean('Current'),
      // "more": figma.boolean('More')
    },
    example: props => <CrumbsTypography size={/* TODO */} />,
  },
);
