import React from 'react';
import { Carousel } from './Carousel';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(Carousel, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=44%3A7651', {
  props: {
    // No matching props could be found for these Figma properties:
    // "showControls": figma.boolean('Show Controls'),
    // "showSliders": figma.boolean('Show Sliders'),
    // "slot": figma.instance('Slot')
  },
  example: props => <Carousel />,
});
