import React from 'react';
import Slider from './Slider.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Slider, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=1066%3A96008', {
  props: {
    showIcon: figma.boolean('Show Icon'),
    showScaleBar: figma.boolean('Show Scale Bar'),
    prefixValue: figma.boolean('Prefix Value'),
    slotPrefix: figma.instance('◆Slot Prefix'),
    slotPostfix: figma.instance('◆Slot Postfix'),
    postfixValue: figma.boolean('Postfix Value'),
  },
  example: props => <Slider />,
});
