import React from 'react';
import { getSelectionCellColumnDef } from './SelectionCell';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  getSelectionCellColumnDef,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A47060',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "showIcon": figma.boolean('Show Icon'),
      // "showCopyButton": figma.boolean('Show Copy Button'),
      // "showButtonClear": figma.boolean('Show Button Clear'),
      // "prefixValue": figma.boolean('Prefix Value'),
      // "slotPrefix": figma.instance('◆Slot Prefix'),
      // "postfixValue": figma.boolean('Postfix Value'),
      // "slotPostfix": figma.instance('◆Slot Postfix')
    },
    example: props => <getSelectionCellColumnDef />,
  },
);
