import React from 'react';
import { FieldText } from './FieldText';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(FieldText, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A45631', {
  props: {
    // These props were automatically mapped based on your linked code:
    disabled: figma.boolean('Disabled'),
    readonly: figma.boolean('Disabled'),
    validationState: figma.enum('Validation', {
      Error: 'error',
      Default: 'default',
      Warning: 'warning',
      Success: 'success',
    }),
    // No matching props could be found for these Figma properties:
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Hovered": "hovered",
    //   "Focused": "focused"
    // }),
    // "value": figma.boolean('Value'),
    // "readOnly": figma.boolean('Read Only')
  },
  example: props => (
    <FieldText
      inputMode={/* TODO */}
      disabled={props.disabled}
      readonly={props.readonly}
      validationState={props.validationState}
    />
  ),
});
