import React from 'react';
import ButtonFunction from './ButtonFunction.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonFunction,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=9%3A7955',
  {
    props: {
      showCounter: figma.boolean('Show Counter'),
      state: figma.enum('State', {
        Default: 'default',
        Hovered: 'hovered',
        Focused: 'focused',
        Pressed: 'pressed',
      }),
      appearance: figma.enum('Appearance', {
        Neutral: 'neutral',
        Primary: 'primary',
        Destructive: 'destructive',
      }),
      showLabel: figma.boolean('Show Label'),
      showIcon: figma.enum('Show Icon', {
        Not: 'not',
        'Icon After': 'icon-after',
        'Icon Before': 'icon-before',
        Only: 'only',
      }),
      loading: figma.boolean('Loading'),
      disabled: figma.boolean('Disabled'),
    },
    example: props => <ButtonFunction />,
  },
);
