import React from 'react';
import ButtonElevated from './ButtonElevated.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonElevated,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=9%3A8352',
  {
    props: {
      state: figma.enum('State', {
        Default: 'default',
        Hovered: 'hovered',
        Focused: 'focused',
        Pressed: 'pressed',
        Disabled: 'disabled',
      }),
      loading: figma.boolean('Loading'),
    },
    example: props => <ButtonElevated />,
  },
);
