import React from 'react';
import ButtonSimple from './ButtonSimple.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ButtonSimple,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=2547%3A196139',
  {
    props: {
      state: figma.enum('State', {
        Default: 'default',
        Hovered: 'hovered',
        Focused: 'focused',
        Pressed: 'pressed',
      }),
      appearance: figma.enum('Appearance', {
        Primary: 'primary',
        Neutral: 'neutral',
        Destructive: 'destructive',
      }),
      showLabel: figma.boolean('Show Label'),
      showIcon: figma.boolean('Show Icon'),
      loading: figma.boolean('Loading'),
      disabled: figma.boolean('Disabled'),
    },
    example: props => <ButtonSimple />,
  },
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(ButtonSimple, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=9%3A4190', {
  props: {
    state: figma.enum('State', {
      Default: 'default',
      Hovered: 'hovered',
      Focused: 'focused',
      Pressed: 'pressed',
    }),
    appearance: figma.enum('Appearance', {
      Primary: 'primary',
      Neutral: 'neutral',
      Destructive: 'destructive',
    }),
    showLabel: figma.boolean('Show Label'),
    showIcon: figma.boolean('Show Icon'),
    loading: figma.boolean('Loading'),
    disabled: figma.boolean('Disabled'),
  },
  example: props => <ButtonSimple />,
});
