import React from 'react';
import { Link } from './Link';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Link, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=4%3A1917', {
  props: {
    // These props were automatically mapped based on your linked code:
    appearance: figma.enum('Appearance', {
      'Invert Neutral': 'invert-neutral',
      Neutral: 'neutral',
      Primary: 'primary',
      Red: 'red',
      Orange: 'orange',
      Yellow: 'yellow',
      Green: 'green',
      Blue: 'blue',
      Violet: 'violet',
      Pink: 'pink',
    }),
    textMode: figma.enum('Text Mode', {
      Default: 'default',
      Accent: 'accent',
      OnAccent: 'on-accent',
    }),
    // No matching props could be found for these Figma properties:
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Focused": "focused",
    //   "Hovered": "hovered"
    // })
  },
  example: props => <Link appearance={props.appearance} textMode={props.textMode} />,
});
