import React from 'react';
import { TagList } from './TagList';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(TagList, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=513%3A48729', {
  props: {
    // No matching props could be found for these Figma properties:
    // "slotTagHiddenContent": figma.instance('◆Slot Tag Hidden Content ')
  },
  example: props => <TagList items={/* TODO */} />,
});
