import React from 'react';
import { FieldColor } from './FieldColor';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FieldColor,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=11024%3A125483',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      open: figma.boolean('Open'),
      disabled: figma.boolean('Disabled'),
      readonly: figma.boolean('Disabled'),
      validationState: figma.enum('Validation', {
        Error: 'error',
        Default: 'default',
        Warning: 'warning',
        Success: 'success',
      }),
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused"
      // }),
      // "value": figma.boolean('Value'),
      // "searchable": figma.boolean('Searchable'),
      // "readOnly": figma.boolean('Read Only')
    },
    example: props => (
      <FieldColor
        open={props.open}
        value={/* TODO */}
        disabled={props.disabled}
        readonly={props.readonly}
        validationState={props.validationState}
      />
    ),
  },
);
