import React from 'react';
import Stepper from './Stepper.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Stepper, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=971%3A91423', {
  props: {
    prefixValue: figma.boolean('Prefix Value'),
    slotPrefix: figma.instance('◆Slot Prefix'),
    postfixValue: figma.boolean('Postfix Value'),
    slotPostfix: figma.instance('◆Slot Postfix'),
  },
  example: props => <Stepper />,
});
