import React from 'react';
import { ProgressBarPage } from './ProgressBarPage';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBarPage,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=4%3A694',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "progress": figma.enum('Progress', {
      //   "100%": "100-",
      //   "90%": "90-",
      //   "80%": "80-",
      //   "70%": "70-",
      //   "60%": "60-",
      //   "50%": "50-",
      //   "40%": "40-",
      //   "30%": "30-",
      //   "20%": "20-",
      //   "10%": "10-",
      //   "0": "0"
      // })
    },
    example: props => <ProgressBarPage inProgress={/* TODO */} />,
  },
);
