import React from 'react';
import { Divider } from './Divider';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Divider, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=11%3A7168', {
  props: {
    // These props were automatically mapped based on your linked code:
    weight: figma.enum('Weight', {
      Regular: 'regular',
    }),
    orientation: figma.enum('Orientation', {
      Horizontal: 'horizontal',
      Vertical: 'vertical',
    }),
  },
  example: props => <Divider weight={props.weight} orientation={props.orientation} />,
});
