import React from 'react';
import { ButtonCopyValue } from './ButtonCopyValue';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonCopyValue,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=20716%3A44087',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Focused": "focused",
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Pressed": "pressed"
      // })
    },
    example: props => <ButtonCopyValue size={/* TODO */} />,
  },
);
