import React from 'react';
import { Drawer } from './Drawer';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Drawer, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A208991', {
  props: {
    // These props were automatically mapped based on your linked code:
    mode: figma.enum('Mode', {
      Regular: 'regular',
      Soft: 'soft',
    }),
    position: figma.enum('Position', {
      Right: 'right',
      Left: 'left',
    }),
  },
  example: props => (
    <Drawer
      open={/* TODO */}
      onClose={/* TODO */}
      mode={props.mode}
      position={props.position}
      content={/* TODO */}
      title={/* TODO */}
    />
  ),
});
