import React from 'react';
import { NotificationCard } from './NotificationCard';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  NotificationCard,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A209942',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      appearance: figma.enum('Apperience', {
        Neutral: 'neutral',
        Error: 'error',
        Warning: 'warning',
        Success: 'success',
      }),
      unread: figma.boolean('Unread'),
      // No matching props could be found for these Figma properties:
      // "showLinkDetails": figma.boolean('Show Link Details'),
      // "showIcon": figma.boolean('Show Icon'),
      // "unread": figma.boolean('Unread'),
      // "slotContent": figma.instance('◆Slot Content'),
      // "showCategory": figma.boolean('Show category'),
      // "showAction": figma.boolean('Show Action'),
      // "showSecondaryButton": figma.boolean('Show Secondary Button'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused"
      // })
    },
    example: props => (
      <NotificationCard
        id={/* TODO */}
        appearance={props.appearance}
        unread={props.unread}
        title={/* TODO */}
        content={/* TODO */}
        date={/* TODO */}
      />
    ),
  },
);
