import React from 'react';
import IconPredefined from './IconPredefined.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  IconPredefined,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A20838',
  {
    props: {
      showBacground: figma.boolean('Show bacground'),
      appearance: figma.enum('Appearance', {
        Primary: 'primary',
        Neutral: 'neutral',
        Red: 'red',
        Orange: 'orange',
        Yellow: 'yellow',
        Green: 'green',
        Blue: 'blue',
        Violet: 'violet',
        Pink: 'pink',
      }),
      decor: figma.enum('Decor', {
        Round: 'round',
        Square: 'square',
      }),
    },
    example: props => <IconPredefined />,
  },
);
