import React from 'react';
import { Toolbar } from './Toolbar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Toolbar, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=25590%3A63833', {
  props: {
    // These props were automatically mapped based on your linked code:
    outline: figma.boolean('Outline'),
    // No matching props could be found for these Figma properties:
    // "outline": figma.boolean('Outline'),
    // "showUpdateButton": figma.boolean('Show Update Button'),
    // "selectable": figma.boolean('Selectable'),
    // "showSearch": figma.boolean('Show Search'),
    // "showFilter": figma.boolean('Show Filter'),
    // "slotExtraButtons": figma.instance('◆Slot Extra Buttons'),
    // "showMoreButton": figma.boolean('Show More Button'),
    // "showExtraButtons": figma.boolean('Show Extra Buttons'),
    // "showFilterButton": figma.boolean('Show Filter Button')
  },
  example: props => <Toolbar outline={props.outline} onRefresh={/* TODO */} />,
});
