import React from 'react';
import { Dropdown } from './Dropdown';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Dropdown, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=3761%3A10192', {
  props: {
    // These props were automatically mapped based on your linked code:
    open: figma.enum('State', {
      Opened: true,
    }),
    // No matching props could be found for these Figma properties:
    // "loading": figma.boolean('Loading')
  },
  example: props => <Dropdown content={/* TODO */} open={props.open} />,
});
