import React from 'react';
import { StatusIndicator, StatusIndicator } from './StatusIndicator';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  StatusIndicator,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A22213',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "appearance": figma.enum('Appearance', {
      //   "Primary": "primary",
      //   "Neutral": "neutral",
      //   "Red": "red",
      //   "Orange": "orange",
      //   "Yellow": "yellow",
      //   "Green": "green",
      //   "Blue": "blue",
      //   "Violet": "violet",
      //   "Pink": "pink"
      // })
    },
    example: props => <StatusIndicator />,
  },
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  StatusIndicator,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A226831',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "color": figma.enum('Color', {
      //   "Primary": "primary",
      //   "Neutral": "neutral",
      //   "Red": "red",
      //   "Orange": "orange",
      //   "Yellow": "yellow",
      //   "Green": "green",
      //   "Blue": "blue",
      //   "Violet": "violet",
      //   "Pink": "pink"
      // }),
      // "load": figma.boolean('Load'),
      // "disabled": figma.boolean('Disabled'),
      // "not": figma.boolean('Not')
    },
    example: props => <StatusIndicator />,
  },
);
