import React from 'react';
import Alert from './Alert.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Alert, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=4619%3A1804', {
  props: {
    showClosed: figma.boolean('Show Closed'),
    showIcon: figma.boolean('Show Icon'),
    showLink: figma.boolean('Show Link'),
    showSecondaryButton: figma.boolean('Show Secondary Button'),
    showAction: figma.boolean('Show Action'),
    slotDescription: figma.instance('◆Slot Description'),
    showTitle: figma.boolean('Show Title'),
    showOutline: figma.boolean('Show Outline'),
    appearance: figma.enum('Appearance', {
      Neutral: 'neutral',
      Info: 'info',
      Primary: 'primary',
      Error: 'error',
      Warning: 'warning',
      Success: 'success',
    }),
  },
  example: props => <Alert />,
});
