import React from 'react';
import { Segment } from './Segment';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Segment, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=3102%3A931', {
  props: {
    // These props were automatically mapped based on your linked code:
    disabled: figma.boolean('Disabled'),
    selected: figma.boolean('Disabled'),
    focusable: figma.enum('State', {
      Focused: true,
    }),
    // No matching props could be found for these Figma properties:
    // "counter": figma.boolean('Counter'),
    // "active": figma.boolean('Active'),
    // "icon": figma.enum('Icon', {
    //   "None": "none",
    //   "Left": "left",
    //   "Only": "only"
    // })
  },
  example: props => (
    <Segment
      value={/* TODO */}
      disabled={props.disabled}
      size={/* TODO */}
      selected={props.selected}
      onClick={/* TODO */}
      focusable={props.focusable}
      onSelectionUpdated={/* TODO */}
    />
  ),
});
