import React from 'react';
import { PaginationSlider } from './PaginationSlider';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  PaginationSlider,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A18191',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "slides": figma.enum('Slides', {
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8",
      //   "9": "9",
      //   "10": "10"
      // })
    },
    example: props => <PaginationSlider total={/* TODO */} page={/* TODO */} onChange={/* TODO */} />,
  },
);
