import React from 'react';
import { CodeEditor } from './CodeEditor';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CodeEditor,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A264340',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hasBackground: figma.boolean('Show Background'),
      // No matching props could be found for these Figma properties:
      // "showRowNumber": figma.boolean('Show RowNumber'),
      // "slotContent": figma.instance('◆Slot Content'),
      // "showScroll": figma.boolean('Show Scroll'),
      // "showBackground": figma.boolean('Show Background'),
      // "showHeadline": figma.boolean('Show Headline')
    },
    example: props => <CodeEditor hasBackground={props.hasBackground} />,
  },
);
