import React from 'react';
import PromoTag from './PromoTag.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  PromoTag,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=15693%3A37477',
  {
    props: {
      slotBeforeContent: figma.instance('◆Slot Before Content'),
      slotAfterContent: figma.instance('◆Slot After Content'),
      showBeforeContent: figma.boolean('Show Before Content'),
      showAfterContent: figma.boolean('Show After Content'),
      showLabel: figma.boolean('Show Label'),
      color: figma.enum('Color', {
        Accent: 'accent',
        Decor: 'decor',
      }),
      appearance: figma.enum('Appearance', {
        Primary: 'primary',
        Neutral: 'neutral',
        Red: 'red',
        Orange: 'orange',
        Yellow: 'yellow',
        Green: 'green',
        Blue: 'blue',
        Violet: 'violet',
        Pink: 'pink',
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hovered: 'hovered',
        Focused: 'focused',
        Pressed: 'pressed',
      }),
    },
    example: props => <PromoTag />,
  },
);
