import React from 'react';
import ProgressBar from './ProgressBar.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(ProgressBar, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=4%3A659', {
  props: {
    progress: figma.enum('Progress', {
      '100%': '100-',
      '90%': '90-',
      '80%': '80-',
      '70%': '70-',
      '60%': '60-',
      '50%': '50-',
      '40%': '40-',
      '30%': '30-',
      '20%': '20-',
      '10%': '10-',
      '0%': '0-',
    }),
  },
  example: props => <ProgressBar />,
});
