import React from 'react';
import { DropZone } from './DropZone';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(DropZone, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A146300', {
  props: {
    // These props were automatically mapped based on your linked code:
    disabled: figma.boolean('Disabled'),
    // No matching props could be found for these Figma properties:
    // "slotContent": figma.instance('◆Slot Content'),
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Hovered": "hovered",
    //   "Focused": "focused",
    //   "DragAccept": "dragaccept"
    // })
  },
  example: props => <DropZone onFilesUpload={/* TODO */} disabled={props.disabled} />,
});
