import React from 'react';
import { Control } from './Control';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Control, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=44%3A7629', {
  props: {
    // These props were automatically mapped based on your linked code:
    variant: figma.enum('Variant', {
      Previous: 'prev',
      Next: 'next',
    }),
    // No matching props could be found for these Figma properties:
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Hovered": "hovered",
    //   "Focused": "focused"
    // })
  },
  example: props => <Control variant={props.variant} />,
});
