import React from 'react';
import { FieldSelectMultiple } from './FieldSelectMultiple';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FieldSelectMultiple,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=2336%3A122361',
  {
    props: {
      postfix: figma.instance('◆Slot Postfix'),
      // Show Icon / Show Button Clear: нет этих имён в макете 6.0.6 (node 2336:122361)
    },
    example: props => (
      <FieldSelectMultiple
        showHintIcon
        showClearButton
        options={[{ value: '1', option: 'Option 1' }]}
        postfix={props.postfix}
      />
    ),
  },
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FieldSelectMultiple,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A47048',
  {
    props: {
      postfix: figma.instance('◆Slot Postfix'),
      // Show Icon / Show Button Clear: нет этих имён в макете 6.0.6 (node 41:47048)
    },
    example: props => (
      <FieldSelectMultiple
        showHintIcon
        showClearButton
        options={[{ value: '1', option: 'Option 1' }]}
        postfix={props.postfix}
      />
    ),
  },
);
