import React from 'react';
import FieldTextArea from './FieldTextArea.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FieldTextArea,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A46995',
  {
    props: {
      yScrolling: figma.boolean('Y scrolling'),
      showCopyButton: figma.boolean('Show Copy Button'),
      showClearButton: figma.boolean('Show Clear Button'),
      showSlotBottom: figma.boolean('Show Slot Bottom'),
      slotBottom: figma.instance('◆ Slot Bottom'),
    },
    example: props => <FieldTextArea />,
  },
);
