import React from 'react';
import FieldText from './FieldText.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FieldText,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=5927%3A137367',
  {
    props: {
      showButtonClear: figma.boolean('Show Button Clear'),
      copyButton: figma.boolean('Copy button'),
      showIcon: figma.boolean('Show Icon'),
      showClearButton: figma.boolean('Show Clear Button'),
      showCopyButton: figma.boolean('Show Copy Button'),
      prefixValue: figma.boolean('Prefix Value'),
      postfixValue: figma.boolean('Postfix Value'),
      slotPrefix: figma.instance('◆Slot Prefix'),
      slotPostfix: figma.instance('◆Slot Postfix'),
      fieldButton: figma.enum('Field Button', {
        Not: 'not',
        Before: 'before',
        After: 'after',
      }),
    },
    example: props => <FieldText />,
  },
);
