import React from 'react';
import FieldTime from './FieldTime.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(FieldTime, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=9209%3A4420', {
  props: {
    slotHoursContent: figma.instance('◆Slot Hours Content'),
    slotMinutesContent: figma.instance('◆Slot Minutes Content'),
    slotSecondsContent: figma.instance('◆Slot Seconds Content'),
    showSeconds: figma.boolean('Show Seconds'),
  },
  example: props => <FieldTime />,
});
