import React from 'react';
import Radio from './Radio.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Radio, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=11%3A6326', {
  props: {
    state: figma.enum('State', {
      Default: 'default',
      Hovered: 'hovered',
      Focused: 'focused',
    }),
    checked: figma.boolean('Checked'),
    disabled: figma.boolean('Disabled'),
  },
  example: props => <Radio />,
});
