import React from 'react';
import { SansLabelL } from './SansLabelL';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(SansLabelL, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A46954', {
  props: {
    // No matching props could be found for these Figma properties:
    // "showQuestion": figma.boolean('Show Question'),
    // "required": figma.boolean('Required'),
    // "showCaption": figma.boolean('Show Caption')
  },
  example: props => <SansLabelL />,
});
