import React from 'react';
import { PageButton, PageButton } from './PageButton';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(PageButton, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A18000', {
  props: {
    // These props were automatically mapped based on your linked code:
    activated: figma.boolean('Activated'),
    // No matching props could be found for these Figma properties:
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Hovered": "hovered",
    //   "Focused": "focused",
    //   "Pressed": "pressed"
    // })
  },
  example: props => <PageButton label={/* TODO */} activated={props.activated} onClick={/* TODO */} />,
});

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(PageButton, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A17958', {
  props: {
    // These props were automatically mapped based on your linked code:
    activated: figma.boolean('Activated'),
    // No matching props could be found for these Figma properties:
    // "state": figma.enum('State', {
    //   "Default": "default",
    //   "Hovered": "hovered",
    //   "Focused": "focused",
    //   "Pressed": "pressed"
    // })
  },
  example: props => <PageButton label={/* TODO */} activated={props.activated} onClick={/* TODO */} />,
});
