import React from 'react';
import { ButtonElevated } from './ButtonElevated';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonElevated,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=9%3A8454',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum('State', {
        Disabled: true,
      }),
      loading: figma.boolean('Loading'),
    },
    example: props => <ButtonElevated disabled={props.disabled} icon={/* TODO */} loading={props.loading} />,
  },
);
