import React from 'react';
import { Droplist } from './DropList';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Droplist, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=15%3A8409', {
  props: {
    // These props were automatically mapped based on your linked code:
    placement: figma.enum('Position', {
      Start: 'top-start',
    }),
    // No matching props could be found for these Figma properties:
    // "placementList": figma.enum('Placement List', {
    //   "Top": "top",
    //   "Right": "right",
    //   "Bottom": "bottom",
    //   "Left": "left"
    // })
  },
  example: props => <Droplist placement={props.placement} items={/* TODO */} />,
});
