import React from 'react';
import { Stepper, Stepper } from './Stepper';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(Stepper, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=971%3A91421', {
  props: {
    // No matching props could be found for these Figma properties:
    // "prefixValue": figma.boolean('Prefix Value'),
    // "slotPrefix": figma.instance('◆Slot Prefix'),
    // "postfixValue": figma.boolean('Postfix Value'),
    // "slotPostfix": figma.instance('◆Slot Postfix')
  },
  example: props => <Stepper steps={/* TODO */} defaultCurrentStepIndex={/* TODO */} />,
});

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(Stepper, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A33632', {
  props: {
    // No matching props could be found for these Figma properties:
    // "slotProdSteps": figma.instance('◆Slot Prod Steps')
  },
  example: props => <Stepper steps={/* TODO */} defaultCurrentStepIndex={/* TODO */} />,
});
