import React from 'react';
import { CollapseBlockSecondary } from './CollapseBlockSecondary';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CollapseBlockSecondary,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A262616',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "slotContent": figma.instance('◆Slot Content'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused"
      // }),
      // "expanded": figma.boolean('Expanded')
    },
    example: props => <CollapseBlockSecondary id={/* TODO */} header={/* TODO */} />,
  },
);
