import React from 'react';
import { Header } from './Header';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(Header, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A262542', {
  props: {
    // No matching props could be found for these Figma properties:
    // "slotTitle": figma.instance('◆Slot Title')
  },
  example: props => <Header title={/* TODO */} />,
});
