import React from 'react';
import { ChipAssist } from './ChipAssist';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ChipAssist,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A147135',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.boolean('Disabled'),
      loading: figma.boolean('Loading'),
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused",
      //   "Pressed": "pressed"
      // }),
      // "showIcon": figma.boolean('Show Icon')
    },
    example: props => (
      <ChipAssist label={/* TODO */} disabled={props.disabled} loading={props.loading} onClick={/* TODO */} />
    ),
  },
);
