import React from 'react';
import { SegmentedControl } from './SegmentedControl';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SegmentedControl,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=8747%3A207443',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum('Width', {
        Full: 'l',
      }),
      width: figma.enum('Width', {
        Auto: 'auto',
        Full: 'full',
      }),
      // No matching props could be found for these Figma properties:
      // "segmenteds": figma.instance('◆Segmenteds')
    },
    example: props => <SegmentedControl items={/* TODO */} size={props.size} width={props.width} />,
  },
);
