import React from 'react';
import { Table } from './Table';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Table, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A226881', {
  props: {
    showPagination: figma.boolean('Show Pagination'),
    showRowsVolume: figma.boolean('Show Rows Volume'),
    showToolbar: figma.boolean('Show Toolbar'),
    showHeader: figma.boolean('Show Header'),
    showFooter: figma.boolean('Show Footer'),
    data: figma.enum('Data', {
      True: 'true',
      Loading: 'loading',
      NoResult: 'noresult',
      NoData: 'nodata',
      Error: 'error',
    }),
  },
  example: props => <Table />,
});
