import React from 'react';
import { FieldContainerPrivate } from './FieldContainerPrivate';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FieldContainerPrivate,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A46683',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      validationState: figma.enum('Validation', {
        Default: 'default',
        Error: 'error',
        Warning: 'warning',
        Success: 'success',
      }),
      disabled: figma.boolean('Disabled'),
      readonly: figma.boolean('Disabled'),
      focused: figma.enum('State', {
        Focused: true,
      }),
      // No matching props could be found for these Figma properties:
      // "readOnly": figma.boolean('Read only')
    },
    example: props => (
      <FieldContainerPrivate
        size={/* TODO */}
        validationState={props.validationState}
        variant={/* TODO */}
        disabled={props.disabled}
        readonly={props.readonly}
        focused={props.focused}
        inputRef={/* TODO */}
      />
    ),
  },
);
