import React from 'react';
import { ToastSystemEvent } from './ToastSystemEvent';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ToastSystemEvent,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A197633',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "queue": figma.enum('Queue', {
      //   ">5": "-5",
      //   "4": "4",
      //   "3": "3",
      //   "2": "2",
      //   "1": "1"
      // })
    },
    example: props => <ToastSystemEvent title={/* TODO */} />,
  },
);
