import React from 'react';
import { ToastUpload } from './ToastUpload';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ToastUpload,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=17432%3A59511',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      collapsed: figma.boolean('Expanded'),
    },
    example: props => (
      <ToastUpload
        status={/* TODO */}
        description={/* TODO */}
        progress={/* TODO */}
        files={/* TODO */}
        collapsed={props.collapsed}
        generalActions={/* TODO */}
      />
    ),
  },
);
