import React from 'react';
import { TreeLine } from './TreeLine';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(TreeLine, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A34680', {
  props: {
    // No matching props could be found for these Figma properties:
    // "showLine": figma.boolean('Show Line'),
    // "lineView": figma.enum('Line View', {
    //   "I": "i",
    //   "T": "t",
    //   "L": "l"
    // })
  },
  example: props => <TreeLine />,
});
