import React from 'react';
import { Alert } from './Alert';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Alert, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=41%3A184592', {
  props: {
    // These props were automatically mapped based on your linked code:
    icon: figma.boolean('Show Icon'),
    appearance: figma.enum('Appearance', {
      Neutral: 'neutral',
      Primary: 'primary',
      Error: 'error',
      Warning: 'warning',
      Success: 'success',
      Info: 'info',
    }),
    outline: figma.boolean('Show Outline'),
    // No matching props could be found for these Figma properties:
    // "showClosed": figma.boolean('Show Closed'),
    // "showIcon": figma.boolean('Show Icon'),
    // "showLink": figma.boolean('Show Link'),
    // "showTitle": figma.boolean('Show Title'),
    // "showSecondaryButton": figma.boolean('Show Secondary Button'),
    // "showAction": figma.boolean('Show Action'),
    // "slotDescription": figma.instance('◆Slot Description'),
    // "showOutline": figma.boolean('Show Outline')
  },
  example: props => (
    <Alert icon={props.icon} description={/* TODO */} appearance={props.appearance} outline={props.outline} />
  ),
});
