import React from 'react';
import { FieldSlider } from './FieldSlider';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FieldSlider,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=1125%3A118047',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.boolean('Disabled'),
      readonly: figma.boolean('Disabled'),
      range: figma.boolean('Range'),
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused"
      // }),
      // "readOnly": figma.boolean('Read Only')
    },
    example: props => (
      <FieldSlider
        disabled={props.disabled}
        readonly={props.readonly}
        range={props.range}
        min={/* TODO */}
        max={/* TODO */}
        step={/* TODO */}
        marks={/* TODO */}
      />
    ),
  },
);
