import React from 'react';
import { ButtonCombo } from './ButtonCombo';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonCombo,
  'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=3761%3A10210',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.boolean('Disabled'),
      loading: figma.boolean('Loading'),
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hovered": "hovered",
      //   "Focused": "focused",
      //   "Pressed": "pressed"
      // })
    },
    example: props => <ButtonCombo disabled={props.disabled} loading={props.loading} items={/* TODO */} />,
  },
);
