import React from 'react';
import Counter from './Counter.story';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Counter, 'https://www.figma.com/design/jtGxAPvFJOMir7V0eQFukN/Snack-UI-Kit-6.0.6?node-id=7%3A4171', {
  props: {
    appearance: figma.enum('Appearance', {
      Primary: 'primary',
      Neutral: 'neutral',
      Red: 'red',
    }),
    color: figma.enum('Color', {
      Accent: 'accent',
      Decor: 'decor',
    }),
  },
  example: props => <Counter />,
});
